### PR TITLE
Windows installer and uninstaller icons

### PR DESCRIPTION
**Pull request by jamj2000**
Hello Tobias, 

I added two icons, for windows installer and windows uninstaller.
I also moved right the veyon image during installation.

image
image

If you like, you can merge.

### CODE REVIEW

**Comment by tobydox** [comment]
Hi José,

welcome on board and thank you very much for your contribution! The changes look promising even though I'd propose to improve the icons a little. Can we combine the logo with some kind of generic installer/uninstaller icons and/or overlays? I think the KDE Breeze icon theme could provide useful images. With the colorized icons users could get confused, especially when browsing the start menu folder with two Veyon logo (one black and one red).

Toby

**Comment by jamj2000** [comment]
Thanks Tobias,

Yet another proposal.

**Comment by jamj2000** [comment]
Another proposal.

**installer.ico**
image

**uninstaller.ico**
image

It looks better for small icons.

**Comment by tobydox** [comment]
I like the first proposal.

**Comment by tobydox** [comment]
Regarding icon sizes: can we skip 256x256 icon and/or use a somehow reduced version? Just asking because adding 300 KB just for an installer icon is quite a lot overhead IMHO.

**Comment by jamj2000** [comment]
Yes, you are right. 

I'm not too excited with the results.

I find out this url: http://nsis.sourceforge.net/%22Orange%22_Modern_UI_Theme

I think is the better solution. What do you think?

**Comment by tobydox** [comment]
Everything looks fine now! Thanks a lot for the contribution!

**Pull request merged**
