### PR TITLE
Debian package generator

### PR DESCRIPTION
**Pull request by jamj2000**
Hello Tobias,

I am working in a  DEB package generator. It uses cmake's CPack module.

If you like, merge.

To generate a deb package appy the rule 
**make package**

### CODE REVIEW

**Comment by tobydox** [comment]
Good work even though I'd like to move this into a separate file such as cmake/CPackDefinitions.cmake and include it in the top level directory CMakeLists.txt. The latter one is already too overloaded and confusing.

**Comment by tobydox** [comment]
I think an INCLUDE statement is missing in CMakeLists.txt ;-)

**Comment by jamj2000** [comment]
Sorry, fixed right now ;)

**Comment by tobydox** [comment]
Thanks! :-)

**Pull request merged**
